### ISSUE TITLE
Handling user-specific layouts

### ISSUE THREAD

**Issue by engram-design** [engram-design/CPNav#1]
While it's great to be able to set the CP navigation globally, the real mission is to have it defined on a per-user basis. This means that you could have a layout for yourself (Admin), your client, other admins, regular members, etc.

But defining a nav layout per-user is quite tedious, instead it'd be better to group them somehow. While initially I wanted to hook this up with User Groups, its tricky as a user can belong to multiple groups, which just wouldn't work when trying to figure out what layout to use. Not to mention these only exist on Craft Pro.

Instead, I've gone down the path of allowing Layouts to be created. You can then edit your nav items for a layout, and assign which users will see this layout.

The idea behind this is you'll define a Default layout, which newly registered users will see, another for your client, and another for admin, etc. This will mean you don't have to manually assign a layout to a user when they are created - that would suck.

Love to hear how people would prefer this to be specified! Any other ideas?

![screen shot 2015-03-15 at 11 48 30 pm](https://cloud.githubusercontent.com/assets/1221575/6656036/13624e4e-cb6e-11e4-8b9c-037a84aa4523.png)

**Comment by lukeholder** [comment]
i think renames of tabs should be global settings of the plugin... a shared naming will make sure when people communicate they are on the same page.

You could make your own layout "groups" ( which only define order and show/hide) with a name, and then allow the user to choose their own layouts with a fieldType on the user profile. that way you could choose the default layout in the feildType if none is set on the user but allow them to choose.

hopefully

**Comment by engram-design** [comment]
Thanks for the comments Luke!

Agreed that users shouldn't be able to change the name - only the Admin can. Hence why only an Admin can access this screen (through the Plugin settings).

I hadn't actually thought of adding it to the user profile screen! Although in some cases you might not want an entry-level member to be able to choose the Admin layout, but thats some logic to figure out.

Nice one!

**Comment by lukeholder** [comment]
you could create a plugin permission to the user to control if someone can change the value of their cp group in their profile maybe?.

**Comment by engram-design** [comment]
I've added this to the main plugin now - users (on Craft Pro) will now get a table to reorder or hide menu items. At this stage, only a single layout is available, which will do for now.

I still think some form user allocation is needed. This is especially the case for sites running Craft Personal and Client - where no user profile exists. Particularly for Craft Client - you'd definitely want a separate layout for the Admin and Client account.

This'll be incorporated soon!

**Comment by engram-design** [comment]
Solved in the [1.7.0 release](https://github.com/engram-design/CPNav/releases/tag/1.7.0).
