### ISSUE TITLE
500 (Internal Server Error)

### ISSUE THREAD

**Issue by happen-studio** [engram-design/CPNav#107]
**Description**
the plugin stopped working (worked perfectly before)
I get an 500 (Internal Server Error) when I hit the "new menu item"-button. 

I already tried to reinstall the plugin without luck. 

**Additional info**
- Plugin version: 4.0.2
- Craft version: 4.1.0.2
- Multi-site:  No

Thanks
![Bildschirmfoto 2022-07-05 um 14 42 25](https://user-images.githubusercontent.com/79902414/177330926-ce40c850-13ec-4897-8c35-608562fe795f.png)

**Comment by engram-design** [comment]
Can you look at the Network tab, find the failing network request? Can you look at the "Preview" tab to see what the error being reported is?

Similar to the below screenshot (the network request will be highlighted in red, and this screenshot is from Formie, but it still applies):

![image](https://user-images.githubusercontent.com/1221575/177332972-23c1cece-e09d-403d-9299-3fb41fe01c3a.png)

**Comment by happen-studio** [comment]
{
    "message": "Syntax error",
    "exception": "yii\\base\\InvalidArgumentException",
    "file": "/var/www/html/haldernpop/craft/vendor/yiisoft/yii2/helpers/BaseJson.php",
    "line": 147,
    "trace": [
        {
            "file": "/var/www/html/haldernpop/craft/vendor/yiisoft/yii2/helpers/BaseJson.php",
            "line": 128,
            "function": "handleJsonError",
            "class": "yii\\helpers\\BaseJson",
            "type": "::"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/verbb/cp-nav/src/models/Settings.php",
            "line": 47,
            "function": "decode",
            "class": "yii\\helpers\\BaseJson",
            "type": "::"
        },
        {
            "function": "verbb\\cpnav\\models\\{closure}",
            "class": "verbb\\cpnav\\models\\Settings",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/yiisoft/yii2/caching/Cache.php",
            "line": 607,
            "function": "call_user_func"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/verbb/cp-nav/src/models/Settings.php",
            "line": 90,
            "function": "getOrSet",
            "class": "yii\\caching\\Cache",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/twig/twig/src/Extension/CoreExtension.php",
            "line": 1607,
            "function": "getFontIconOptions",
            "class": "verbb\\cpnav\\models\\Settings",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/craftcms/cms/src/helpers/Template.php",
            "line": 101,
            "function": "twig_get_attribute"
        },
        {
            "file": "/var/www/html/haldernpop/craft/storage/runtime/compiled_templates/20/2053b9dd7086c4ece25d52fd687d4b01.php",
            "line": 112,
            "function": "attribute",
            "class": "craft\\helpers\\Template",
            "type": "::"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/twig/twig/src/Template.php",
            "line": 394,
            "function": "doDisplay",
            "class": "__TwigTemplate_1015184a5cc3639fe2b5889ec9ebf552",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/twig/twig/src/Template.php",
            "line": 367,
            "function": "displayWithErrorHandling",
            "class": "Twig\\Template",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/twig/twig/src/Template.php",
            "line": 379,
            "function": "display",
            "class": "Twig\\Template",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/twig/twig/src/TemplateWrapper.php",
            "line": 40,
            "function": "render",
            "class": "Twig\\Template",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/twig/twig/src/Environment.php",
            "line": 277,
            "function": "render",
            "class": "Twig\\TemplateWrapper",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/craftcms/cms/src/web/View.php",
            "line": 414,
            "function": "render",
            "class": "Twig\\Environment",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/verbb/cp-nav/src/controllers/NavigationController.php",
            "line": 158,
            "function": "renderTemplate",
            "class": "craft\\web\\View",
            "type": "->"
        },
        {
            "function": "actionGetHudHtml",
            "class": "verbb\\cpnav\\controllers\\NavigationController",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/yiisoft/yii2/base/InlineAction.php",
            "line": 57,
            "function": "call_user_func_array"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/yiisoft/yii2/base/Controller.php",
            "line": 178,
            "function": "runWithParams",
            "class": "yii\\base\\InlineAction",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/yiisoft/yii2/base/Module.php",
            "line": 552,
            "function": "runAction",
            "class": "yii\\base\\Controller",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/craftcms/cms/src/web/Application.php",
            "line": 301,
            "function": "runAction",
            "class": "yii\\base\\Module",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/craftcms/cms/src/web/Application.php",
            "line": 625,
            "function": "runAction",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/craftcms/cms/src/web/Application.php",
            "line": 280,
            "function": "_processActionRequest",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/vendor/yiisoft/yii2/base/Application.php",
            "line": 384,
            "function": "handleRequest",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/haldernpop/craft/web/index.php",
            "line": 12,
            "function": "run",
            "class": "yii\\base\\Application",
            "type": "->"
        }
    ],
    "error": "Syntax error"
}

**Comment by engram-design** [comment]
Looks to be a Craft 4.1 change causing this. Fixed in [4.0.3](https://github.com/verbb/cp-nav/releases/tag/4.0.3)

**Comment by happen-studio** [comment]
thank you very much for the fast fix.
