### ISSUE TITLE
Reconstructing the project files when CP-Nav is active trigger an error

### ISSUE THREAD

**Issue by scandella** [engram-design/CPNav#108]
### Describe the bug

Using Craft 4.x, when I try to reload the project files from the 'reload all' button in the "Config project" of the utilities panel, an error occur and the process fail.
In the log:
`2022-07-21 12:04:15 [web.ERROR] [yii\base\ErrorException:2] yii\base\ErrorException: Undefined array key "permissions" in /myproject/dev/vendor/verbb/cp-nav/src/services/Layouts.php:159`

When the CP-Nav is inactive, the issue does not occur.

Best, 

### Steps to reproduce

1. reload the project files
2. an error occur

### Craft CMS version

Craft Pro 4.1.4.1

### Plugin version

4.0.3

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [4.0.4](https://github.com/verbb/cp-nav/releases/tag/4.0.4)
