### ISSUE TITLE
Add composer.json for package management and publish on Packagist

### ISSUE THREAD

**Issue by ErikSwan** [engram-design/CPNav#11]
I use a workflow for developing my Craft projects that makes heavy use of package management and automation for deployment (using Git post-receive hooks and [Gulp](http://www.gulpjs.com)). For managing some of the other dependencies that my project relies on (mostly on the front end, things like normalize.css, jQuery, SASS, etc.) I use existing package managers liked [npm](http://www.npmjs.com), [bundler](http://bundler.io), and [bower](http://bower.io).

This allows me to maintain a git repository for the project with only source code committed and simply do a `git push production` at which point the workflow I have set up will automatically pull in any dependencies for the project and build everything (compile SASS, minimize JS, etc.). It would be very useful to have plugins support this workflow so that I don't have to manually check out a copy of the plugin and keep it up to date - instead I can just specify that I require this plugin and that will happen automatically.

PHP has the [Composer](https://getcomposer.org) package manager, and Brad Bell has hinted that [Craft will likely support installation in this manner in a future release of Craft](http://craftcms.stackexchange.com/questions/1454/what-would-it-take-to-make-craft-composer-based#comment2373_1465).

It would be great to see this plugin add a composer.json file and be published on [Packagist](https://packagist.org). That way the above workflow would be supported, and users of the plugin can simply add a composer.json file of their own in their project directory and specify CPNav as a dependency:
```
{
    "require": {
        "engram-design/cpnav": "~1.6"
    }
}
```

And then upon deployment pull in the plugin: `composer install`

Here is a good starting point for the composer.json file that I've put together. It makes use of the Composer installers package to automatically install the plugin to the correct Craft directory:
```
{
    "name": "engram-design/cpnav",
    "type": "craft-plugin",
    "description": "A Craft CMS plugin to help manage your Control Panel navigation.",
    "keywords": ["craft","plugin", "cp", "navigation"],
    "homepage": "https://github.com/engram-design/CPNav",
    "license": "MIT",
    "authors": [
        {
            "name": "Josh Crawford",
            "email": "josh@engramdesign.com.au",
            "homepage": "http://engramdesign.com.au/",
            "role": "Developer"
        }
    ],
    "require": {
        "composer/installers": "~1.0"
    } 
}
```
Then, to support proper versioning, you would need to [tag appropriate commits](https://help.github.com/articles/creating-releases/) in this repository to designate plugin releases. Packagist will crawl the repo and automatically make these specific commits available as versions accessible via the "require" syntax shown above.

This workflow should be standard for Craft plugins in my opinion and probably will be once Craft itself is available as a Composer package on Packagist (hopefully soon—once this happens you would then specify the required Craft version in the `require` object in the composer.json file).

If you would be willing to do this it would be awesome and help with promoting a sane development workflow in the Craft community.

Thanks!

*Note for anyone else who want's this type of functionality __now__*: 
it can be replicated using [Git submodules](http://git-scm.com/book/en/v2/Git-Tools-Submodules), which is what I'm currently using to avoid having to commit a working copy of CPNav into my project repo, but it's a bit hacky and proper Composer support would be better.

**Comment by engram-design** [comment]
Great idea @ErikSwan. Like you say, hopefully the Craft boys include this sort of functionality with the plugin store, and future Craft versions.

I haven't had much experience with Composer - only npm, so can totally understand the need for this.

I'll look at incorporating this ASAP!

**Comment by engram-design** [comment]
@ErikSwan So much for ASAP haha! This has now been organised. Thanks so much for your detailed description by the way, it really helped, and hopefully will be a handy guide to anyone else!
