### ISSUE TITLE
Cp clear cache and error

### ISSUE THREAD

**Issue by wmdhosting** [engram-design/CPNav#115]
### Describe the bug

CP clear cache plugin icon not visible when cp is activated.. 
https://github.com/mmikkel/CpClearCache-Craft

tryed on   upgrade craft and fresh install  

and this error showing. 
verbb\cpnav\models\Navigation::getBadgeCount(): Return value must be of type int, string returned - /home/craft4wmd/vendor/verbb/cp-nav/src/models/Navigation.php: 155.

That worked well on craft 3

### Steps to reproduce

1.  install https://github.com/mmikkel/CpClearCache-Craft
2. instal cp nav
3. 

### Craft CMS version

4.3  4.2.8

### Plugin version

4.0.6

### Multi-site?

y

**Comment by wmdhosting** [comment]
found one more. thing

plugins dont show in sublevel..
![Snag_113b379b](https://user-images.githubusercontent.com/76176291/198033500-245d4146-22c1-496c-816c-a778a6ae02a2.png)

**Comment by engram-design** [comment]
This would be down to how the [CpClearCache](https://github.com/mmikkel/CpClearCache-Craft) is registering its nav items. They currently use an event:

```php
Event::on(Cp::class, Cp::EVENT_REGISTER_CP_NAV_ITEMS, function (RegisterCpNavItemsEvent $event) {
    $event->navItems['mmikkel/cpclearcache'] = [
        'label' => \Craft::t('app', 'Clear Caches'),
        'fontIcon' => 'trash',
        'url' => 'mmikkel/cpclearcache'
    ];
});
```

Instead of a function:

```
public function getCpNavItem(): ?array
{
    ...
}
```

Should be fixed, along with the plugin subnav issue in [4.0.7](https://github.com/verbb/cp-nav/releases/tag/4.0.7)
