### ISSUE TITLE
Composer error when deploying to production

### ISSUE THREAD

**Issue by tyssen** [engram-design/CPNav#123]
### Question

I've run through an upgrade of a site locally and eventually got everything working. I'm now trying to deploy the changes to production and have done `composer install` which installs everything OK, followed by `php craft up` which gives me:
> You need to be on at least Control Panel Nav 3.0.17 before you can update to Control Panel Nav 4.0.10.

What needs to be done to resolve that?

**Comment by engram-design** [comment]
Sounds like a project config mishap more than anything, but looks like you've resolved it?

**Comment by tyssen** [comment]
I exported the local db into production. Luckily, it's not a site that gets updated very often so my local copy of the db is still current with the content on production.
