### ISSUE TITLE
Error in log - must be of type array, null given

### ISSUE THREAD

**Issue by philipboomy** [engram-design/CPNav#125]
### Describe the bug

Hi

I am seeing this a lot in my weblog. 

[cp-nav] array_key_exists(): Argument #2 ($array) must be of type array, null given - /home/ploi/www.website.co.uk/vendor/verbb/cp-nav/src/helpers/Permissions.php: 215.

### Steps to reproduce

Just browse around in the CP and the error should appear in the log

### Craft CMS version

4.4.13

### Plugin version

4.0.10

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/cp-nav:"dev-craft-4 as 4.0.10"`.

**Comment by engram-design** [comment]
Fixed in [4.0.11](https://github.com/verbb/cp-nav/releases/tag/4.0.11)
