### ISSUE TITLE
Craft 5 > Beta 11

### ISSUE THREAD

**Issue by wmdhosting** [engram-design/CPNav#130]
### Describe the bug

![Snag_aeea7ee](https://github.com/verbb/cp-nav/assets/76176291/a3972eea-4835-4e2e-b3b1-7a54ec634277)

Just info

### Steps to reproduce

1. Just install. 

### Craft CMS version

Craft 5 Beta 11

### Plugin version

5.0.0-beta.1

**Comment by engram-design** [comment]
We've been largely waiting for UI changes to settle down before making our updates to the new sidebar menu. Particularly the collapsable behaviour which is now native Craft behaviour.

Fixed in [5.0.0-beta.2](https://github.com/verbb/cp-nav/releases/tag/5.0.0-beta.2)
