### ISSUE TITLE
CLear cache icon

### ISSUE THREAD

**Issue by wmdhosting** [engram-design/CPNav#131]
### Describe the bug

I checked with mmikkel
![Snag_fe5d793](https://github.com/verbb/cp-nav/assets/76176291/bc8fbe11-f592-46b1-8eba-fa0776d9eda4)

NO icon so when saving settings in admin, saving takes 15+sec longer

https://github.com/mmikkel/CpClearCache-Craft/issues/16

Re: the missing icon, I'm pretty sure this must be a bug in CP Nav for Craft 5, where it looks like CP Nav doesn't handle existing [nav items using font icons](https://github.com/mmikkel/CpClearCache-Craft/blob/1ed155059dcdab2de7dc85c427d6299a3e829b6a/src/CpClearCache.php#L106) properly. You should create an issue over at [CP Nav's repo](https://github.com/verbb/cp-nav) for that.

### Steps to reproduce

1. Install Clear cache
2. enable CP nav

### Craft CMS version

5

### Plugin version

5.0.0-beta.2

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/cp-nav:"dev-craft-5 as 5.0.0-beta.2"`
