### ISSUE TITLE
CP Nav  Longer page load

### ISSUE THREAD

**Issue by wmdhosting** [engram-design/CPNav#132]
### Describe the bug

Im testing Craft 5 commerce and other things

And use simple  example to show whats happenign on all site settings pages.. 

When i add Order Status in commerce , that takes  less than 1 sec  normally >> i tested on few servers.. 

When i test  with CP Nav enabled  i get this.. 

![Snag_373ea3](https://github.com/verbb/cp-nav/assets/76176291/dcb3650b-97b9-420e-9002-7464f5821305)

When i disable  CP Nav >>  times is  2 times less

![Snag_384e2f](https://github.com/verbb/cp-nav/assets/76176291/da5540e4-c478-48fd-9a3b-102662bafa94)

I disabled all other plugins but stay like this.. 

I know its not just CP Nav related 
Any pointers how to debug this  waiting for server to respond
I tryed to make all settings same as on servers where it opens under 1s . but still same
And site is run on Dedicated server without resource limit..

### Steps to reproduce

1. Instll CP nav.  here is example with  adding Commerce >>  Order status .. but work similar everywhere..

### Craft CMS version

5.0.4

### Plugin version

5.0.0-beta.2

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/cp-nav:"dev-craft-5 as 5.0.0-beta.2"`

**Comment by wmdhosting** [comment]
hm.. tested few times. now seem takes even more time.. 

with
![Snag_79f465](https://github.com/verbb/cp-nav/assets/76176291/4464bd1b-6720-4760-811b-78e802402f07)

WIthout
![Snag_7a1674](https://github.com/verbb/cp-nav/assets/76176291/9b4a11da-dbab-4db1-bfc1-36f634963ab1)

**Comment by engram-design** [comment]
Just to be clear, this is when saving order statuses for Commerce? I’m sure it happens at other times, but just ensuring that I’m relocating things reliably.

**Comment by wmdhosting** [comment]
Yes, creating  new order statuses  for Commerce 
I taken that as example as it simple page.. 
admin/commerce/settings/orderstatuses

**Comment by engram-design** [comment]
Not seeing any difference on my end I'm afraid. My latest fix brought down the time (locally) from 11s to 4.5s, and that's the same whether the plugin is disabled or not.

**Comment by wmdhosting** [comment]
ok thx..
