### ISSUE TITLE
Does not load Layout anymore,

### ISSUE THREAD

**Issue by wmdhosting** [engram-design/CPNav#134]
### Describe the bug

Im on composer require verbb/cp-nav:"dev-craft-5 as 5.0.0-beta.2"

And upgraded to 5.1.7 Craft 

Seems now its does not load  Default layout.. it just behave as there is no CP Nav..
-------------------------------------------------

IF i try to reset Defauly layout >> Then i get it all empty..  no menu items..

### Steps to reproduce

Try with 5.1.7 Craft 

### Craft CMS version

5.1.7

### Plugin version

5.0.0-beta.2

**Comment by engram-design** [comment]
It's probably worth getting on the stable [5.0.0](https://github.com/verbb/cp-nav/releases/tag/5.0.0) release now.

I can't replicate this I'm afraid. Any errors in your log files?

**Comment by wmdhosting** [comment]
i updated to  stable .  and OK now :)

I normally update all.. but perhaps  stable version did not update for some reason... last time i done all uodates..
