### ISSUE TITLE
Creating Layout Throws Error

### ISSUE THREAD

**Issue by adrianjean** [engram-design/CPNav#137]
### Describe the bug

I'm getting the following error when trying to create a new layout. I have uninstalled and reinstalled the plugin, and still receive this error.

`Cannot assign string to property verbb\cpnav\models\Layout::$permissions of type ?array`

### Steps to reproduce

1. Click New Layout
2. Provide a name, in my case I just used "Test"
3. Click Save — the error appears as a CraftCMS notice. 

### Craft CMS version

Craft Pro 5.2.3

### Plugin version

5.0.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
Should be fixed in [5.0.1](https://github.com/verbb/cp-nav/releases/tag/5.0.1)
