### ISSUE TITLE
[Craft 5] "Server error occured" message

### ISSUE THREAD

**Issue by thanasispsarros** [engram-design/CPNav#138]
### Describe the bug

I have an issue where almost any action I take in the CP Nav UI, like enabling/disabling or moving a nav item triggers a `Server error occured` error notification. Af far as I can tell this does not have any effect on any functionality, but still is a bit concerning.

Worth noting that this issue is while running the project on DDEV. I haven't found anything meaningful on the logs, but maybe I'm not looking in the right place.

### Steps to reproduce

1.  Open the CP Nav UI.
2. Toggle the status of one of the nav items.

### Craft CMS version

 5.2.5

### Plugin version

5.0.1

### Multi-site?

No

### Additional context

This happens on multiple Craft 5 projects, on DDEV locally, with dev mode on OR off. I Haven't tested on production, since this would mean allowing admin changes.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/cp-nav:"dev-craft-5 as 5.0.1"`.

**Comment by engram-design** [comment]
Fixed in [5.0.2](https://github.com/verbb/cp-nav/releases/tag/5.0.2)
