### ISSUE TITLE
[Craft 5] "First letter" icon not showing

### ISSUE THREAD

**Issue by thupsi** [engram-design/CPNav#139]
### Describe the bug

I have an issue where the `Craft Icon` -> `First letter` option results in a missing icon. 

### Steps to reproduce

1. On a new or existing nav item select "First Letter" from the "Craft Icon" dropdown.
2. The icon is missing:
![image](https://github.com/verbb/cp-nav/assets/19857599/816fcf58-c2ee-48db-9e0d-816aec945bec)

### Craft CMS version

5.2.5

### Plugin version

5.0.1

### Multi-site?

No

**Comment by thupsi** [comment]
Strangely enough, I just discovered that, _if I don't select any icon_, the first letter icon is displayed correctly. 🤷

![image](https://github.com/verbb/cp-nav/assets/19857599/aee6ed28-da3b-4dad-9cc6-b13266986573)

![image](https://github.com/verbb/cp-nav/assets/19857599/6b862519-d579-4141-bad0-55a47ff10cd9)

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/cp-nav:"dev-craft-5 as 5.0.1"`.

**Comment by engram-design** [comment]
Fixed in [5.0.2](https://github.com/verbb/cp-nav/releases/tag/5.0.2)
