### ISSUE TITLE
Error when all tabs removed

### ISSUE THREAD

**Issue by lindseydiloreto** [engram-design/CPNav#14]
If you have no tabs enabled, you can trigger an error by going to `/admin`.

**Expected behavior:**

- Be forced to view the standard Dashboard, even though it's disabled.

**Steps to reproduce:**

1. Disable **all** tabs
2. Go to `/admin`
3. Witness error message

![error](https://cloud.githubusercontent.com/assets/5309692/8173577/8e71b5bc-1384-11e5-9938-9f428246902f.png)

**Comment by lindseydiloreto** [comment]
Admittedly, this is an edge case. But I have a valid use-case for it...

We use a standard **base install**, which we pull from a git repo every time we start a new project. The base install has all of our standard defaults already configured.

On virtually every project these days, I disable the Dashboard using _this_ awesome plugin. But in the base install, **no sections have yet been created**.

I'd love to disable the Dashboard in the base install, thus saving myself the trouble of doing it later. :)

**Comment by engram-design** [comment]
@lindseydiloreto Thanks for reporting this - it's an edge case, but certainly needs to be addressed. I'll integrate this in the (soon-to-be-released) next round of updates.

**Comment by lindseydiloreto** [comment]
Sweet, looking forward to it! :)

**Comment by engram-design** [comment]
This has been resolved since [1.7.0 release](https://github.com/engram-design/CPNav/archive/1.7.0.zip). Thanks again for submitting this one!

**Comment by lindseydiloreto** [comment]
Nice, thanks man!
