### ISSUE TITLE
500 Error on rename

### ISSUE THREAD

**Issue by JamesNock** [engram-design/CPNav#15]
Hi guys, I'm getting an Integrity constraint violation when trying to rename a menu item in Craft Pro 2.4.2702. Full response here:

<h1>CDbException</h1>
<p>CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1048
 Column 'newWindow' cannot be null. The SQL statement executed was: UPDATE `cpnav_navs` SET `enabled
`=:yp0, `order`=:yp1, `manualNav`=:yp2, `newWindow`=:yp3, `id`=:yp4, `layoutId`=:yp5, `handle`=:yp6,
 `prevLabel`=:yp7, `currLabel`=:yp8, `prevUrl`=:yp9, `url`=:yp10, `dateCreated`=:yp11, `dateUpdated`
=:yp12, `uid`=:yp13 WHERE `cpnav_navs`.`id`=5. Bound with :yp0=1, :yp1=4, :yp2=0, :yp3=NULL, :yp4=5,
 :yp5=1, :yp6='charge', :yp7='Charge', :yp8='Charge', :yp9='charge', :yp10='charge', :yp11='2015-10-31
 11:28:34', :yp12='2015-10-31 11:31:39', :yp13='651f9529-a8d6-421b-9bf6-4d42c510cbc1' (/Users/James/Sites
/craft.dev/craft/app/framework/db/CDbCommand.php:358)</p><pre>#0 /Users/James/Sites/craft.dev/craft/app/framework/db/ar/CActiveRecord.php(1754): CDbCommand->execute()
#1 /Users/James/Sites/craft.dev/craft/app/framework/db/ar/CActiveRecord.php(1128): CActiveRecord-
>updateByPk('5', Array)
#2 /Users/James/Sites/craft.dev/craft/app/framework/db/ar/CActiveRecord.php(810): CActiveRecord-
>update(NULL)
#3 /Users/James/Sites/craft.dev/craft/plugins/cpnav/services/CpNav_NavService.php(152): CActiveRecord-
>save()
#4 /Users/James/Sites/craft.dev/craft/plugins/cpnav/controllers/CpNavController.php(136)
: Craft\CpNav_NavService->saveNav(Object(Craft\CpNav_NavModel))
#5 /Users/James/Sites/craft.dev/craft/app/framework/web/actions/CInlineAction.php(49): Craft
\CpNavController->actionSaveNav()
#6 /Users/James/Sites/craft.dev/craft/app/framework/web/CController.php(308): CInlineAction-
>runWithParams(Array)
#7 /Users/James/Sites/craft.dev/craft/app/framework/web/CController.php(286): CController-
>runAction(Object(CInlineAction))
#8 /Users/James/Sites/craft.dev/craft/app/framework/web/CController.php(265): CController-
>runActionWithFilters(Object(CInlineAction), Array)
#9 /Users/James/Sites/craft.dev/craft/app/framework/web/CWebApplication.php(282): CController-
>run('saveNav')
#10 /Users/James/Sites/craft.dev/craft/app/etc/web/WebApp.php(805): CWebApplication->runController
('cpNav/saveNav')
#11 /Users/James/Sites/craft.dev/craft/app/etc/web/WebApp.php(275): Craft\WebApp->_processActionRequest
()
#12 /Users/James/Sites/craft.dev/craft/app/framework/base/CApplication.php(184): Craft\WebApp-
>processRequest()
#13 /Users/James/Sites/craft.dev/craft/app/index.php(62): CApplication->run()
#14 /Users/James/Sites/craft.dev/htdocs/index.php(19): require_once('/Users/James/Si...'
)
#15 {main}</pre>

Any ideas?

**Comment by engram-design** [comment]
This should be fixed in the [1.7.0 release](https://github.com/engram-design/CPNav/releases/tag/1.7.0) - but please let me know if you're still having issues.

**Comment by ewanlyle** [comment]
Still having this issue:

2016/05/26 14:31:14 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'newWindow' cannot be null. The SQL statement executed was: UPDATE `craft_cpnav_navs` SET `enabled`=:yp0, `order`=:yp1, `manualNav`=:yp2, `newWindow`=:yp3, `id`=:yp4, `layoutId`=:yp5, `handle`=:yp6, `prevLabel`=:yp7, `currLabel`=:yp8, `prevUrl`=:yp9, `url`=:yp10, `icon`=:yp11, `dateCreated`=:yp12, `dateUpdated`=:yp13, `uid`=:yp14 WHERE `craft_cpnav_navs`.`id`=9. Bound with :yp0=1, :yp1=5, :yp2=0, :yp3=NULL, :yp4=9, :yp5=1, :yp6='formbuilder2', :yp7='FormBuilder 2', :yp8='Enquiries', :yp9='formbuilder2', :yp10='formbuilder2', :yp11='iconSvg-formbuilder2', :yp12='2016-05-26 14:20:33', :yp13='2016-05-26 14:31:14', :yp14='60119d3c-7b22-4bd0-9a57-5676b8e84ce7'' in C:\xampp\htdocs\sites\misc\craft\app\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\sites\misc\craft\app\framework\db\ar\CActiveRecord.php(1754): CDbCommand->execute()
#1 C:\xampp\htdocs\sites\misc\craft\app\framework\db\ar\CActiveRecord.php(1128): CActiveRecord->updateByPk('9', Array)
#2 C:\xampp\htdocs\sites\misc\craft\app\framework\db\ar\CActiveRecord.php(810): CActiveRecord->update(NULL)
#3 C:\xampp\htdocs\sites\misc\craft\plugins\cpnav\services\CpNav_NavService.php(63): CActiveRecord->save(false)
#4 C:\xampp\htdocs\sites\misc\craft\plugins\cpnav\controllers\CpNav_NavController.php(100): Craft\CpNav_NavService->save(Object(Craft\CpNav_NavModel))
#5 C:\xampp\htdocs\sites\misc\craft\app\framework\web\actions\CInlineAction.php(49): Craft\CpNav_NavController->actionSave()
#6 C:\xampp\htdocs\sites\misc\craft\app\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\sites\misc\craft\app\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\sites\misc\craft\app\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\sites\misc\craft\app\framework\web\CWebApplication.php(282): CController->run('save')
#10 C:\xampp\htdocs\sites\misc\craft\app\etc\web\WebApp.php(815): CWebApplication->runController('cpNav/nav/save')
#11 C:\xampp\htdocs\sites\misc\craft\app\etc\web\WebApp.php(285): Craft\WebApp->_processActionRequest()
#12 C:\xampp\htdocs\sites\misc\craft\app\framework\base\CApplication.php(185): Craft\WebApp->processRequest()
#13 C:\xampp\htdocs\sites\misc\craft\app\index.php(62): CApplication->run()
#14 C:\xampp\htdocs\sites\misc\public_html\index.php(19): require_once('C:\\xampp\\htdocs...')
#15 {main}
REQUEST_URI=/sites/misc/public_html/index.php/admin/actions/cpNav/nav/save
HTTP_REFERER=http://localhost/sites/misc/public_html/admin/cpnav
---
2016/05/26 14:31:14 [trace] [system.CModule] Loading "errorHandler" application component
in C:\xampp\htdocs\sites\misc\craft\app\etc\web\WebApp.php (593)

******************************************************************************************************

Running Craft CMS 2.6.2776 and Control Panel Nav 1.7.4

Possible issue with cases of filenames?

**Comment by engram-design** [comment]
Have you tried uninstalling the plugin and installing again? Seems like it might be an issue with the database table.
