### ISSUE TITLE
Nukes new sidebar icons in Craft 2.5

### ISSUE THREAD

**Issue by ijy** [engram-design/CPNav#16]
Looks like it needs a slight tweak for Craft 2.5. Installing sees the pretty icons in the sidebar wiped out:

![cp-nav-craft25](https://cloud.githubusercontent.com/assets/434593/11422434/cfe18150-9433-11e5-9169-a6b5a6ec37f0.png)

**Comment by engram-design** [comment]
Craft 2.5 is not officially supported yet, but will be very soon. Its undergoing a full rewrite to make it even better!

**Comment by ijy** [comment]
Sounds great! I'm a week ahead of the expected 2.5 release data but I just couldn't resist. :) Whilst I'm putting together the current project I thought I'd highlight any issues I found. Any ideas when you're likely to drop the update?

**Comment by engram-design** [comment]
Yep, I knew people would start checking it with 2.5 soon :smiley: Looking to release before 2.5, so likely in the next few days.

**Comment by ijy** [comment]
Awesome! I'll keep a look out for it. :)

**Comment by engram-design** [comment]
Sorry for the delay - the [1.7.0 release](https://github.com/engram-design/CPNav/releases/tag/1.7.0) fixes this by supporting Craft 2.5
