### ISSUE TITLE
How do I change the icon of a CPnav item

### ISSUE THREAD

**Issue by shealan** [engram-design/CPNav#18]
The example image shows nice icons but my items show placeholder letters as an icon. Is it possible to choose icons somehow?

**Comment by engram-design** [comment]
The icons come from either Craft's core pages (Dashboard, Entries, etc), or from Plugins. At this stage, any manual nav items you create cannot have a custom icon, and will instead get that custom placeholder icon. Its on the roadmap to allow custom icons!

**Comment by shealan** [comment]
Thanks for the clarification. Look forward to that feature being added. Thanks for a great plugin!

**Comment by engram-design** [comment]
Added in [1.7.5](https://github.com/engram-design/CPNav/releases/tag/1.7.5).
