### ISSUE TITLE
Getting siteUrl throws a PHP notice : Array to string conversion 

### ISSUE THREAD

**Issue by slelorrain** [engram-design/CPNav#19]
Hello, 

I just updated CPNav to 1.7.3 and i'm getting an "array to string conversion" notice.

According to the documentation, siteUrl accepts: "A string set to any valid URL, or an array that maps locale IDs to locale-specific URLs" (https://craftcms.com/docs/config-settings#siteUrl)

Regards

![siteurl_notice](https://cloud.githubusercontent.com/assets/988120/13390841/2ab18a70-ded1-11e5-84ae-99717e1bd997.png)

**Comment by engram-design** [comment]
Thanks for getting in touch. Can you confirm your `siteUrl` value as defined in your `general.php` file? Is it an array or a string?

**Comment by slelorrain** [comment]
It's an array (containing 'en', 'fr', 'de' and 'es' as key)

I also made a [commit](https://github.com/slelorrain/CPNav/commit/1f962d3c8810995cf64ba4bf13d28e054fa92b27), do you want a pull request ?

**Comment by engram-design** [comment]
Awesome - one step ahead!
