### ISSUE TITLE
When Max Levels is set to 1, the parent page can still be set when adding another url

### ISSUE THREAD

**Issue by joshangell** [engram-design/CPNav#2]
Whilst you can't nest items via the drag and drop interface, you can still set the parent page when adding a new url which is slightly confusing.

Lovely plugin though :smile:

**Comment by engram-design** [comment]
Thanks Josh! Not sure I know what you mean, although I've not had the chance to mess around with Max Levels on any site yet, so forgive my inexperience. If you have a max level of 1, there shouldn't be any parent page to link to?

**Comment by joshangell** [comment]
Ok my bad, totally got the wrong plugin here forgive me ... !

**Comment by engram-design** [comment]
Haha, thats okay! No worries :)
