### ISSUE TITLE
Errors on latest Craft CMS

### ISSUE THREAD

**Issue by thomasvankerckvoorde** [engram-design/CPNav#21]
<img width="1418" alt="screenshot 2016-03-10 10 18 15" src="https://cloud.githubusercontent.com/assets/2323270/13664834/a75de548-e6a9-11e5-98e7-8be3ba1abd18.png">

This is solved now, cpnav.js had to be CPNav.js. Same for the css file.
+ I had no other member groups, seems you need to have at least one.

**Comment by engram-design** [comment]
Out of interest, did you update from a previous version? You also don't necessarily need a member group, unless you want to create different layouts - which they rely on member groups.

**Comment by thomasvankerckvoorde** [comment]
No, I just updated craft to 2.6 today and AFTER that I installed cpnav for the first time.
