### ISSUE TITLE
Translation / locale support.

### ISSUE THREAD

**Issue by juskaiser** [engram-design/CPNav#22]
It seems like the plugin breaks the locale translations of the labels for default menu items. For example, prior to installing the plugin, the _Dashboard_ link in the French locale was translated as _Tableau de bord_. After installing the plugin it reverted to the translation for the English locale which is my primary locale.

My suggestion would be that this plugin follows Craft's default behavior and checks the site static translation files to see if there is a localized translation for the menu item label. In this way standard menu items would continue to be translated on a per locale basis as they have been, and it would also allow for adding locale translation for custom menu items added via the plugin.

I realize that I can override the menu item name in a layout for a user group by manually changing the menu item label, but this isn't ideal because it is possible to have members of a single user group that have different locale preferences. So choosing one locale for a user group and manually translating it isn't a very good option.

I realize this request probably entails a lot of work but I just wanted to mention it because I thought it would be a good addition for future versions. Other than that, this plugin is awesome. Thanks for the great resource.

**Comment by engram-design** [comment]
Thats a great point, I hadn't taken that into consideration as each menu label is stored in the locale they're generated in. However, while they may be stored in one locale, its a quick fix to have them outputted in the destination locale - its something I considered while doing it - just didn't take into account being able to switch.

Note that if you label something that doesn't have a static translation, it'll appear in the locale you specify. For example - if you re-label a menu item with `My menu item`, this will be its name for all locales. You could easily add your own static translations to cater for this however.

In any case, would you like to try out the latest master for me? I've tested through a few locales, but just to be safe, would be great to know if you're still having issues.

**Comment by engram-design** [comment]
Added in [1.7.5](https://github.com/engram-design/CPNav/releases/tag/1.7.5), but let me know if you have any further issues! Closing for now.

**Comment by juskaiser** [comment]
Tried it after the update. It is working great. Thanks for implementing this feature.
