### ISSUE TITLE
"POST param “permissions” doesn’t exist." when attempting to add new layout.

### ISSUE THREAD

**Issue by RyanGittins** [engram-design/CPNav#24]
Hey there!  I love the plugin, but I am having some difficulty.

When I attempt to add a new layout, I press the `+ New layout` button, fill in a name, and press the `Create` button.  Then, Craft reports `An unknown error occurred.` and the console reports `POST param “permissions” doesn’t exist.` on the attempt to post to `/admin/actions/cpNav/layout/new`.

When I investigate the request, I do see that the required `permissions` key is missing, leaving only `name=test&id=`.  Investigating the plugin's code, it certainly appears that on line 55 of `CpNav_LayoutController.php` the key is required by means of `getRequiredPost()`.

I'm using the newest version, and any help would be appreciated.  Thanks!

**Comment by green-plastic** [comment]
It seems you need to have user groups set up for this to work. Permissions should only be required when there are user groups.

**Comment by engram-design** [comment]
Fixed in [1.7.6](https://github.com/engram-design/CPNav/releases/tag/1.7.6). I have to say, Layouts are probably a little useless without User Groups, but that shouldn't stop you from creating them.
