### ISSUE TITLE
Custom Icons Not Working

### ISSUE THREAD

**Issue by mikegraham00** [engram-design/CPNav#34]
### Description
Craft 3. I have selected custom icons for my CP Nav items, but only seeing the placeholder letters. This works correctly in the C2 version with the same icon files.

### Steps to reproduce

1. Create a CP Nav item
2.Add a custom SVG icon

### Additional info

- Plugin version: 2.0.3
- Craft version: 3.0.0-RC10.1

**Comment by engram-design** [comment]
@mikegraham00 I've tried a few SVG icons on my end, and all working well. Are you able to send through what you're testing? Not sure if it makes a difference, but I've noticed on some other Craft 3 installs that SVG's haven't worked that well if they're missing the XML definition `<?xml version="1.0" encoding="utf-8"?>` above it.

Are you trying to add the icon to a custom nav item, plugin or built-in nav item?

**Comment by mikegraham00** [comment]
Thanks for the response. I tried adding the XML declaration to an icon before uploading but didn't seem to help.

Here is an example icon I'm trying to use.
`<svg xmlns="http://www.w3.org/2000/svg" width="16" height="14" viewBox="0 0 16 14">
  <path fill="#FFFFFF" d="M1,0 C0.44,0 0,0.44 0,1 C0,1.56 0.44,2 1,2 C1.56,2 2,1.56 2,1 C2,0.44 1.56,0 1,0 Z M4,0 L4,2 L16,2 L16,0 L4,0 Z M1,4 C0.44,4 0,4.44 0,5 C0,5.56 0.44,6 1,6 C1.56,6 2,5.56 2,5 C2,4.44 1.56,4 1,4 Z M4,4 L4,6 L16,6 L16,4 L4,4 Z M1,8 C0.44,8 0,8.44 0,9 C0,9.56 0.44,10 1,10 C1.56,10 2,9.56 2,9 C2,8.44 1.56,8 1,8 Z M4,8 L4,10 L16,10 L16,8 L4,8 Z M1,12 C0.44,12 0,12.44 0,13 C0,13.56 0.44,14 1,14 C1.56,14 2,13.56 2,13 C2,12.44 1.56,12 1,12 Z M4,12 L4,14 L16,14 L16,12 L4,12 Z"/>
</svg>`

Thanks again.

**Comment by engram-design** [comment]
Well, thats even more bizarre, as that exact icon is working for me. See attached.

What browser/OS are you using? Any other plugins installed that could mess with things?

![screen shot 2018-02-21 at 9 01 34 am](https://user-images.githubusercontent.com/1221575/36451669-eba0167c-16e5-11e8-812a-ba4fa8c943f4.png)

**Comment by mikegraham00** [comment]
Yeah really weird. Must be something funky in my setup though SVGs in that volume are working fine on the front end...I'm on Chome/Mac.

**Comment by engram-design** [comment]
I'll see what I can do to reproduce the issue, also on Chrome/Mac.

Can you confirm if you're trying to add the icon to a custom nav item, plugin or built-in nav item?

**Comment by mikegraham00** [comment]
Thanks. Trying to add it to a custom nav item.

**Comment by mikegraham00** [comment]
I may try it on a fresh install to see if I can isolate the issue. Can you show me your working asset volume setup?

One thing I didn't mention is that I am using multisite on this install. Don't think that is the cause, but just wanted to be clear.

**Comment by mikegraham00** [comment]
I found the issue. I was using @webroot in my file system path for this volume. I removed that and it immediately worked. Thanks for looking into it. Sorry for the time waster. Love the plugin.
