### ISSUE TITLE
Nav item doesn't display "sel" class (Craft 3)

### ISSUE THREAD

**Issue by tyler-deboer** [engram-design/CPNav#36]
### Description
Sidebar nav items no longer have `class="sel"` when they're active, so I'm not able to see at a glance which section of the control panel I'm currently in.

### Additional info
- Plugin version: 2.0.3
- Craft version: 3.0.0-RC14

**Comment by engram-design** [comment]
This should be fixed in [2.0.4](https://github.com/verbb/cp-nav/releases/tag/2.0.4).
