### ISSUE TITLE
CP Nav causing other plugins sub-nav to disappear.

### ISSUE THREAD

**Issue by mikestecker** [engram-design/CPNav#37]
### Description
CP Nav causing other plugins sub-nav to disappear.

See discussion: https://github.com/nystudio107/craft-seomatic/issues/22

### Steps to reproduce

1. Install CP-Nav
2. Install SEOmatic

### Additional info

- Plugin version: 2.0.3
- Craft version: 3.0-RC15

**Comment by engram-design** [comment]
This should be fixed in [2.0.4](https://github.com/verbb/cp-nav/releases/tag/2.0.4).
