### ISSUE TITLE
Stopped working on RC17.1 to 3.0.1 update

### ISSUE THREAD

**Issue by juresrpcic** [engram-design/CPNav#39]
I had a working setup with CP-NAV but it's not working anymore since updating to the 3.0.1 release of Craft. If I go to `admin/cp-nav` and press one of the lightswitches (turn a menu item on or off), I temporarily see the stored custom menu on the left, but it disappears again when clicking on a menu item / away from `admin-cp-nav`.

**Comment by ljclark** [comment]
Getting the above issue too, ever since upgrading to 3.0.1

**Comment by engram-design** [comment]
This should be fixed in [2.0.4](https://github.com/verbb/cp-nav/releases/tag/2.0.4).
