### ISSUE TITLE
Manual link not being added

### ISSUE THREAD

**Issue by lindseydiloreto** [engram-design/CPNav#4]
First of all, let me say **thank you!!** This plugin is brilliant. I'd had the thought to build something similar, but you've far surpassed anything that I would have put together. :)

Here's the bug I'm hitting...

As a test, I tried to create a new external link. For the label, I used "Peanut Butter", and for the URL, I used "http://www.jif.com/". I clicked the button, it said "Menu item added", but it didn't actually add the menu item. I peeked into the database, and it doesn't look like the data was added to the `cpnav_navs` table.

I've got a couple other minor feedback notes, but I'll open those up as separate tickets. Thanks! :)

**Comment by engram-design** [comment]
Interesting. I've tested this many times myself, and has worked pretty well. Will continue to investigate!

**Comment by lindseydiloreto** [comment]
If you try it with that exact data (Peanut Butter / http://www.jif.com/), and it works for you, let me know. I can investigate locally if need be.

**Comment by engram-design** [comment]
Yep - looks like it has a problem with spaces is the name. This will be fixed ASAP!

**Comment by lindseydiloreto** [comment]
Awesome, thanks Josh! :)

**Comment by engram-design** [comment]
A silly mistake on my behalf - fixed!

**Comment by lindseydiloreto** [comment]
Excellent!!  :+1:
