### ISSUE TITLE
Craft3: Calling unknown method: craft\elements\db\UserQuery::client() in CP

### ISSUE THREAD

**Issue by sergeifilippov** [engram-design/CPNav#40]
### Description

CP Yii toolbar reporting an error 
```
verbb\cpnav\services\CpNavService::modifyCpNav Calling unknown method: craft\elements\db\UserQuery::client()
```

![dashboard -2018-04-10 16-27-17](https://user-images.githubusercontent.com/123676/38536202-0b532da8-3cdc-11e8-9d4d-b4efd5193ad3.png)

### Steps to reproduce

1. Install plugin
2. Load Plugin
3. Create  profile

### Additional info

- Plugin version: 2.0.3
- Craft version: 3.0.1

**Comment by engram-design** [comment]
This should be fixed in [2.0.4](https://github.com/verbb/cp-nav/releases/tag/2.0.4).
