### ISSUE TITLE
Display issue - conflicting with Architect Plugin?

### ISSUE THREAD

**Issue by ljclark** [engram-design/CPNav#41]
### Description

Getting some funky characters in my side bar whenever I turn this plugin on whilst having Architect enabled (v.2.2.8)

![screen shot 2018-04-11 at 15 23 39](https://user-images.githubusercontent.com/8060816/38623021-805357a2-3d9c-11e8-9bd4-27fea097c0a6.png)

Also tried removing the custom svg icons from the new entries in the sidenav to see if it was those messing it up, and makes no difference either. 

### Steps to reproduce

1. Install CP Nav
2. Turn CP Nav on
3. Install Architect 
4. Turn Architect on

### Additional info

- CP Nav Plugin version: 2.0.4
- Craft version: 3.0.2

**Comment by mikestecker** [comment]
That bug is happening with other plugins that have an option on the sidebar. I have SEOmatic and Sprout Forms, but not Architect and it's happening to me.

**Comment by chillibe** [comment]
Same with SEOmatic.

**Comment by engram-design** [comment]
Struggling to reproduce this actually. Can you provide any information on browser and OS? Does this happen in the reverse order (installing SEOmatic/Architect first, then CP Nav)? Does this occur instantly when you install CP Nav, or only after messing around?

**Comment by ljclark** [comment]
It actually only looks to be happening on my staging and local environements now, which is odd as it was doing it on all 3 at one point. Here are the environment details (all the same across each one)

- PHP version 7.1.17
- MySQL 5.5.60
- Imagick 3.4.3 (ImageMagick 6.8.9-9)
- Craft Pro 3.0.5
- Yii 2.0.15.1
- Twig 2.4.8
- Guzzle 6.3.3
- Imagine 0.7-dev

**Plugins:** 
![screen shot 2018-05-08 at 13 24 59](https://user-images.githubusercontent.com/8060816/39756972-410eddc8-52c3-11e8-9c12-7b6ecdcaf364.png)

Browser is Firefox Quantum 59.0.2 (64-bit), also occuring on Safari Version 11.0.1 (12604.3.5.1.1) & Chrome Version 66.0.3359.139

Running MacOS Sierra 10.12.6 (16G29)

Issues occur instantly after other plugins, but only seems to affect those items in the sidebar that are below a custom one added via your plugin. If you disable your plugin, the issue goes. 

No errors in the console log either :/

**Comment by engram-design** [comment]
Fixed in [2.0.6](https://github.com/verbb/cp-nav/releases/tag/2.0.6).
