### ISSUE TITLE
Allow for a simple divider between sections of links.

### ISSUE THREAD

**Issue by engram-design** [engram-design/CPNav#45]

**Comment by SayChi** [comment]
This sounds awesome, really gives the menu a calmer look. Especially when you got a bunch of plugins that keep expanding the menu.
Maybe this gives it a kickstart, this css looks like a pretty good divider to me (on the entries item for example)
```
#nav-entries {
    border-bottom: 1px solid #999fa6;
    padding-bottom: 8px;
    margin-bottom: 8px;
}
```

**Comment by engram-design** [comment]
@SayChi Yep, this will be coming in a larger overhaul of the plugin, for its next major version, which includes a lot more flexibility with groups, nesting, etc.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/cp-nav/releases/tag/3.0.0).
