### ISSUE TITLE
Type mismatch in install.php

### ISSUE THREAD

**Issue by dbrookes** [engram-design/CPNav#46]
https://github.com/verbb/cp-nav/blob/craft-3/src/migrations/Install.php#L99

This prevents install if you're using Postgres

` > create table {{%cpnav_layout}} ...Exception: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "isDefault" is of type boolean but default expression is of type integer`

Also `manualNav` and `newWindow`

**Comment by engram-design** [comment]
Sorry about this, fixed in [2.0.5](https://github.com/verbb/cp-nav/releases/tag/2.0.5).
