### ISSUE TITLE
Weird layout issue when accessing the CPNav settings 

### ISSUE THREAD

**Issue by frontedbe** [engram-design/CPNav#51]
### Description
Looks like some CSS hasn't been loaded? But no specific lack of resource or js errors to see in console

[View screenshot](https://cl.ly/soEt)

### Additional info

- Plugin version: 2.0.8
- Craft version: 3.0.14

**Comment by frontedbe** [comment]
From the Settings > Plugins, the 'settings' link href to **/admin/settings/plugins/cp-nav** but should href to **admin/cp-nav**, I guess?

[view screenshot](https://cl.ly/so5O)

**Comment by jeffaglenn** [comment]
I'm getting this as well. Nothing critical, just odd. Once you hit `admin/cp-nav` everything is fine.

**Comment by engram-design** [comment]
Yep, sorry about that all - should be fixed in the latest craft-3 branch, and will push to a new release shortly.

**Comment by engram-design** [comment]
Should be fixed as of [2.0.9](https://github.com/verbb/cp-nav/releases/tag/2.0.9)
