### ISSUE TITLE
Select SVG from Craft defaults (feature request)

### ISSUE THREAD

**Issue by KatieMFritz** [engram-design/CPNav#54]
I like the improved interface in 2.0.9!

Default icons are working for me again in new and regenerated menus. 👍 

Something that's tricky/time consuming for me is finding the right SVG icons for my custom links. Some ideas:
- Somehow allow the user to select from Craft's default SVG icons (in addition to uploading a custom one)
- At least link to where the Craft icons can be downloaded, or how they can be referenced

**Comment by engram-design** [comment]
I'll see what can be done here. Unfortunately, Craft uses an icon font internally, so its not as easy as just using those.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/cp-nav/releases/tag/3.0.0).

**Comment by KatieMFritz** [comment]
Dude, you rock.

**Comment by KatieMFritz** [comment]
I love it. 😍

![Screen Shot 2020-03-01 at 8 35 34 AM](https://user-images.githubusercontent.com/7085184/75626701-ca461000-5b97-11ea-9d0a-aad82af00313.png)
