### ISSUE TITLE
Control Panel Nav Removes  Item

### ISSUE THREAD

**Issue by TonyGarand** [engram-design/CPNav#55]
### Description

When adding a url in entries/leadPages to the nav it will display properly until you move anywhere besides the navigate tab

![screen shot 2018-11-13 at 11 19 46 am](https://user-images.githubusercontent.com/40325421/48439768-f5ef7d80-e73b-11e8-9488-ad6134422d31.png)
![screen shot 2018-11-13 at 11 20 01 am](https://user-images.githubusercontent.com/40325421/48439769-f5ef7d80-e73b-11e8-8c3f-5ef52ba323bc.png)

### Steps to reproduce

1. Create item entries/leadPages
2. Move away from the navigate tab

### Additional info

- Plugin version: 2.0.9
- Craft version: 3.0.31

**Comment by engram-design** [comment]
Hmmm, I can't seem to replicate this no matter what I do! I notice that it's seemingly only that specific nav item, for instance you've hidden Categories and Services, and they're correctly hidden on both screenshots.

Have you tried re-creating the Lead Pages custom nav item?

**Comment by engram-design** [comment]
This should be fixed in [3.0.0](https://github.com/verbb/cp-nav/releases/tag/3.0.0) thanks to a major refactor with how this was all done.
