### ISSUE TITLE
Getting Twig runtime error: Variable "layouts" does not exist when in dev mode

### ISSUE THREAD

**Issue by mikeebee** [engram-design/CPNav#56]
### Description

After installing I went into the plugins menu and clicked on the plugin and I get this error when in dev mode

```
Twig Runtime Error
Variable "layouts" does not exist.
in <sitePath>/vendor/verbb/cp-nav/src/templates/index.html
```

### Steps to reproduce

1. Put site into dev mode
2. Install plugin
3. Click on plugin in settings menu

### Additional info

- Plugin version: 2.0.9
- Craft version: 3.0.32 (Pro, dev mode)

I am also having a similar issue (variable not existing) with your field-manager plugin, I will wait to see the resolution of this one as they will likely be linked.

### Update
This only happens in dev mode and seems to effect all Verbb plugins

Thanks!

**Comment by engram-design** [comment]
I believe this was an issue with having the [Cloner](https://github.com/verbb/cloner) plugin installed.

[Cloner 1.0.1](https://github.com/verbb/cloner/releases/tag/1.0.1) fixes this.
