### ISSUE TITLE
Project Config support

### ISSUE THREAD

**Issue by KatieMFritz** [engram-design/CPNav#57]
It would be convenient to be able to export and import layouts, like you can export/import fields with Field Manager. Of course, some urls might not exist in the new site, but I think just a general warning when importing would be okay for that, at least as a MVP. 

I just configured a sweet layout on my dev site and thought that project.yaml would push it to staging, but I guess it's in the database instead.

**Comment by engram-design** [comment]
Would support for Project Config be preferable, as opposed to a full import/export solution from scratch? I'm not sure how many people out there allow non-admins to manage CP Nav, and whether it'd be a pain to set on dev environments.

**Comment by KatieMFritz** [comment]
Yes, project config support would be great and would take care of most of my use cases, at least.

**Comment by stenvdb** [comment]
+1 on this

**Comment by benface** [comment]
+1 for saving nav layouts in project config!

**Comment by dmatthams** [comment]
+1 for this!

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/cp-nav/releases/tag/3.0.0).

**Comment by KatieMFritz** [comment]
Partying so hard! 🎉
