### ISSUE TITLE
SVG icons not reproduced correctly

### ISSUE THREAD

**Issue by echantigny** [engram-design/CPNav#58]
### Description
Here's 2 screenshots, with and without the plugin activated.  Customer Lists is your own Wishlist plugin.

If I regenerate the navigation, it fixes the 2 icons, but as soon as I switch page, the issue comes back.

![2019-06-13 11_47_50-Plugins - Great Boardgames](https://user-images.githubusercontent.com/4933333/59447642-93de2000-8dd1-11e9-8281-129ffc3cc395.png)
![2019-06-13 11_48_21-Plugins - Great Boardgames](https://user-images.githubusercontent.com/4933333/59447643-93de2000-8dd1-11e9-9754-ff8fe97c1a2f.png)

### Additional info

- Plugin version: 2.0.9
- Craft version: Craft Pro 3.1.29

**Comment by BryceBubbles** [comment]
I'm also experiencing this on

- Craft version: 3.3.12
- Plugin version: 2.0.9

**Comment by engram-design** [comment]
I can't seem to reproduce this on a number of browsers. Can you confirm OS and browser? I assume you're not overwriting any of these icons with custom SVGs? Hard to see from the screenshot, but the icon starting with `C:\64` seems to point to Windows.

Any chance you're able to inspect this icon element and report the content?

If you are using a custom SVG, can you confirm your asset volume settings, and also any SVG you're using as a replacement?

**Comment by engram-design** [comment]
This should be fixed in [3.0.0](https://github.com/verbb/cp-nav/releases/tag/3.0.0).
