### ISSUE TITLE
Custom icon on S3 volume not working

### ISSUE THREAD

**Issue by shornuk** [engram-design/CPNav#59]
### Description
Trying to add a custom icon to a custom nav item. Icon gets uploaded to assets fine, but when I save the nav item it give an error `Getting unknown property: craft\awss3\Volume::path`

### Additional info

- Plugin version: Latest
- Craft version: Latest

**Comment by engram-design** [comment]
Will have to test this out - I would've thought things would be similar to the local volume, so that does seem odd at first glance....

**Comment by engram-design** [comment]
Fixed in [3.0.0](https://github.com/verbb/cp-nav/releases/tag/3.0.0).
