### ISSUE TITLE
Manual link - Ability to "Open in new window"

### ISSUE THREAD

**Issue by lindseydiloreto** [engram-design/CPNav#6]
I see on your roadmap that you plan to give the option for manual links to "Open in a new window"... Just wanted to let you know that this has my vote, I could see this feature being quite useful! :)

**Comment by engram-design** [comment]
I'm not 100% committed to this just yet, because I'd need to inject some javascript onto each CP page to watch for this. It's a similar situation for [#3](https://github.com/engram-design/CPNav/issues/3). We don't have any control over the actual menu item element other than the anchor's text and href values,

**Comment by lindseydiloreto** [comment]
Fair enough, I'm sure I won't be the last person to request it. :)

On the plus side, the amount of JS needed is actually pretty small.

**Comment by engram-design** [comment]
It's not the amount (in fact, you can just use `craft()->request->redirect()` for the most part). I just feel hesitant about it. But it's something that's pretty well-needed at the moment, so I'll get over it! :)

**Comment by engram-design** [comment]
This has been added in the latest version (1.6). Thanks for the suggestion - it sped things along a little :)

**Comment by lindseydiloreto** [comment]
Awesome!!! Thanks Josh!

**Comment by lindseydiloreto** [comment]
Thanks so much for adding this feature, it's working great!

Only one small bug... It looks like all links are now getting saved with "Open in New Window" by default. Even if you don't activate the lightswitch, it still saves as enabled.

**Comment by engram-design** [comment]
Yep, just noticed this too! Fixed in the latest release :)

**Comment by lindseydiloreto** [comment]
Fantastic, thanks! :)
