### ISSUE TITLE
Only displaying most recent nav item

### ISSUE THREAD

**Issue by theAdhocracy** [engram-design/CPNav#63]
When I go to the Navigation settings I can see all of the additional nav items that I've added, but only the most recent instance (in this case "Update Website" is actually displayed. Also, strangely, it always appears in the same position, between Entries and Globals, no matter where I move it to or what order I put nav items in. Example:

![image](https://user-images.githubusercontent.com/7009462/71892452-d1751280-3140-11ea-9dc3-1c81cd2e6b3c.png)

The moment that I edit anything (say, move two labels around, toggle visibility etc.) they all appear in the sidebar correctly, but only for as long as the Settings panel is open. The moment I navigate away it reverts to the layout shown above.

- Plugin version: 2.0.9
- Craft version: 3.3.19

**Comment by bleepsandblops** [comment]
Same issue here!

**Comment by engram-design** [comment]
This should be fixed in [3.0.0](https://github.com/verbb/cp-nav/releases/tag/3.0.0) thanks to a major refactor with how this was all done.
