### ISSUE TITLE
Feature request: nested menu items

### ISSUE THREAD

**Issue by KatieMFritz** [engram-design/CPNav#64]
**Context:** The CP nav menu is a handy place to put lots of shortcuts, but it can also get visually overwhelming when everything is on the same level. 

**Request:** Allowing nesting/progressive reveal of menu items to make it easier for editors/authors/admins to parse the available links.

An example of the desired behavior:

![Screen Shot 2020-01-30 at 11 27 09 AM](https://user-images.githubusercontent.com/7085184/73468978-a5217000-4353-11ea-8e53-3b0b0d97d819.png)

Other thoughts:
- Could use a toggle arrow or some other visual affordance that the section is expandable.
- I personally don't care whether nested items have icons or not.
- Persistent state (expanded/collapsed) might be nice.
- One level of nesting is probably ideal. 
- Parent links could just be toggles, or go to the first child item *and* open the submenu (I think this is the current behavior for plugins with nested menus), or be normal links *and* open the submenu.

**Use case**

Part of a sample nav menu:

- Content
  - Entries
  - Categories
  - Tags
  - Assets
- Tools
  - Retour
  - Feed Me
- Settings
  - Searchit
  - Seomatic
  - Webhooks

**Comment by engram-design** [comment]
Thanks! I was going to roll this in to the latest update, but it proved a much bigger task. Adding to the todo list

**Comment by JayBox325** [comment]
@engram-design How has this task progressed this year? This is something I'm keen to add, but I've managed to make do with headings for now.

**Comment by engram-design** [comment]
Very pleased to announce this is now possible in [4.0.0-beta.2](https://github.com/verbb/cp-nav/releases/tag/4.0.0-beta.2) for Craft 4. You can manage all subnav items from Craft and plugins, by moving them in or out of their default position. For example, if you wanted to move Orders out of Commerce > Orders. You can of course add your manual items inside or as parents of items.

Secondly, there'a also now the option per navigation item to control the subnav behaviour - including core Craft subnav items like "GraphQL", and plugins like Commerce.

- Only open subnav items when the parent page is active (Craft default behaviour).
- Always have subnav items open and visible.
- Add a toggle next to each parent menu item to show/hide the subnav items. Will also remember the state!

You can also manage this globally in the plugin settings if you want everything to have the sam behaviour.
