### ISSUE TITLE
Some icons are missing or wrong

### ISSUE THREAD

**Issue by dennisfrank** [engram-design/CPNav#68]
### Description

Thank you for the Craft Icon select. It’s a great feature! 

Unfortunately some icons are currently not working or are incorrect. 

![image](https://user-images.githubusercontent.com/65968/73981937-9fb7bd00-4933-11ea-9515-73283fea6ab7.png)

### Steps to reproduce

1. Choose the `image` icon for example.
2. It is presented as a globe.

Because the `data-icon` attribute gets the wrong value `image` instead of `asset`. 

There are more examples…

### Additional info

- Plugin version: 3.0.2
- Craft version: 3.4.4.1

### Pull Request

I have made a [pull request](https://github.com/verbb/cp-nav/pull/67) in which I have updated the icons: #67 

Additionally I have sorted the icons by label, removed duplicates and added name variants to the label.

I hope you can use the PR and maybe merge it!

**Comment by engram-design** [comment]
Thanks! Merged and added in [3.0.3](https://github.com/verbb/cp-nav/releases/tag/3.0.3)
