### ISSUE TITLE
Can’t restore original icon

### ISSUE THREAD

**Issue by dennisfrank** [engram-design/CPNav#69]
### Description

When I change the label of an item with a default icon, the original icon gets replaced by an icon with the initial letter of the label. How do I get the original icon back?

The same issue occurs when I change the icon. There seems to be no way to restore the original icon.

### Additional info

- Plugin version: 3.0.2
- Craft version: 3.4.4.1

**Comment by engram-design** [comment]
What nav items are you editing? I'm testing with Dashboard, Entries and a few other 'stock' ones, and not seeing this. When you're editing an item, is the "Craft Icon" field populated? You're not using a custom icon as well?

But you are correct, if you change the "Craft Icon" value, it'll overwrite the default icon, with no way to recover the original one (short of regenerating the nav items). I'll add that in at some point.

**Comment by JayBox325** [comment]
I have just changed the title of SEOMatic to "SEO" and it lost the original icon, without touching the icon.

Also, I removed "commerce" from the nav for a minute. Then when I put it back in it didn't have the original icon and there was no way of getting it back.

**Comment by engram-design** [comment]
If this is still an issue, can you report the following - Look in your `cpnav_navigation` database table and find the row for the associated cp nav item that isn't showing correctly. Can you paste the content's of the row here, and I'm interested in the "icon" column.

I also assume this default icon remains after you navigate away from the CP Nav settings - not just when previewing the nav?

**Comment by engram-design** [comment]
Should be fixed in [4.0.0-beta.2](https://github.com/verbb/cp-nav/releases/tag/4.0.0-beta.2) for Craft 4.
