### ISSUE TITLE
Globals Not Showing Up?

### ISSUE THREAD

**Issue by jacobgraf** [engram-design/CPNav#70]
I just added a Global, but Globals is not showing up in the sidebar. I can access Globals by manually typing in /admin/globals but it doesn't show in the menu. I've checked the settings for CP Nav and I don't even see Globals as a toggle-able option?

**Comment by engram-design** [comment]
Looks like this is when adding your very first global, so it's not refreshing the nav in that instance.

It now does as of [3.0.5](https://github.com/verbb/cp-nav/releases/tag/3.0.5), as I've improved the changed-nav detection behaviour. You'll however need to reset your nav, after which is should pick up changes better for next time.
