### ISSUE TITLE
Project config issue in 3.0.5

### ISSUE THREAD

**Issue by frontedbe** [engram-design/CPNav#71]
### Description
When surfing to /admin/ and having allowAdminChanges set to false, "I get the Changes to the project config are not possible while in read-only mode." anywhere in the CMS.
[view screenshot](https://share.getcloudapp.com/KouWe0Yk)

Works in 3.0.4, errors in 3.0.5

### Steps to reproduce

1. allowAdminChanges => false
2. /admin/

### Additional info

- Plugin version: 3.0.5
- Craft version: 3.4.8

**Comment by engram-design** [comment]
Should be fixed in [3.0.6](https://github.com/verbb/cp-nav/releases/tag/3.0.6)
