### ISSUE TITLE
SEOmatic cp-nav item disappears after switching site/language

### ISSUE THREAD

**Issue by frontedbe** [engram-design/CPNav#72]
### Description

[view screen-capture](https://share.getcloudapp.com/p9uKKNm5)

### Steps to reproduce

1. Install SEOmatic + CP Nav
2. Create multiple sites
2. Go to SEOmatic > switch site > watch the SEOmatic cp nav item disappear (also out of the cpnav_navigation table)

### Additional info

- Plugin version: 3.0.6
- Craft version: 3.4.8

**Comment by engram-design** [comment]
Fixed in [3.0.7](https://github.com/verbb/cp-nav/releases/tag/3.0.7)
