### ISSUE TITLE
Possible bug - originalNavHash continually changes in project.yaml

### ISSUE THREAD

**Issue by j-greig** [engram-design/CPNav#74]
### Description

We have 2 developers using the plugin in conjunction with project config.

The `originalNavHash` value seems to be continually changing in project.yaml, even though neither of us is changing the nav settings at /admin/cp-nav.

### Additional info

- Plugin version: 3.0.7
- Craft version: 3.4.9

![image](https://user-images.githubusercontent.com/616194/78886825-be7f2080-7a56-11ea-9b09-3fcf35bb2504.png)

**Comment by engram-design** [comment]
Should be fixed in [3.0.11](https://github.com/verbb/cp-nav/releases/tag/3.0.11)

**Comment by j-greig** [comment]
Thank you 😊
