### ISSUE TITLE
Some icons render path instead of icon

### ISSUE THREAD

**Issue by nathanbookout** [engram-design/CPNav#75]
### Description

Similar to previously closed issue [#58 ](https://github.com/verbb/cp-nav/issues/58)

Upon first re-order of the menu, certain icons display the local file system path to the icon.

![menu](https://user-images.githubusercontent.com/3406956/79264372-143e3900-7e5a-11ea-8ad4-cf0880b2e2a2.PNG)

See above - Commerce and SEOmatic are not displaying their icons. Inspecting some of the menu items yields the following:

![code](https://user-images.githubusercontent.com/3406956/79265106-31273c00-7e5b-11ea-92a2-6cd7698fb4e8.PNG)

### Steps to reproduce

1. Spin up a local test server with Craft
2. Install one of the problematic plugs, such as Commerce
3. Install cp-nav plugin
4. Attempt to re-order nav; item icon for Commerce should break.

### Additional info

- Plugin version: 3.0.8.2
- Craft version: 3.4.15

**Comment by engram-design** [comment]
Should be fixed in [3.0.11](https://github.com/verbb/cp-nav/releases/tag/3.0.11)
