### ISSUE TITLE
Unable to upload custom icons - After update to	3.0.11

### ISSUE THREAD

**Issue by DaveBeirne** [engram-design/CPNav#76]
### Description

I updated both CraftCms and Control Nav plugin today to **Control Panel Nav 3.0.11** & **Craft Pro 3.4.17.1.**

When i click on Custom Icon  **"Choose"** button for SVG asset, nothing happens after clicking, for both new nav items or old ones.

### Steps to reproduce

1. Updated craft to latest version 3.4.17.1 also plugin needed updating
2.  Clicked plugin Control Panel Nav > New Menu Item  > + Choose  >Nothing happens ...
3. Tested on Chrome / Safari / Edge same issue

### Additional info

- Plugin version: 3.0.11
- Craft version: Craft Pro 3.4.17.1

I had no issues before updating

<img width="1086" alt="Screenshot 2020-04-26 at 17 57 16" src="https://user-images.githubusercontent.com/1081103/80314191-f8d31680-87e7-11ea-9980-3c47d82dbd36.png">

**Comment by engram-design** [comment]
Fixed in [3.0.12](https://github.com/verbb/cp-nav/releases/tag/3.0.12)

**Comment by DaveBeirne** [comment]
Thank you
