### ISSUE TITLE
{siteUrl} support

### ISSUE THREAD

**Issue by lindseydiloreto** [engram-design/CPNav#8]
Sorry for blowing up your Github issues... :)

It would be great if the URL supported `{siteUrl}` to reference front-end pages. This is crucial for multi-environment setups.

![example](https://cloud.githubusercontent.com/assets/5309692/6759916/35fa16e4-cf01-11e4-969d-ee1ac48ee01a.png)

**Comment by lindseydiloreto** [comment]
To clarify, I mean the ability to pull `config` values in as part of the URL...

![screen shot 2015-03-20 at 1 05 23 pm](https://cloud.githubusercontent.com/assets/5309692/6760040/5791ea2e-cf02-11e4-8998-655b66aaf203.png)

![screen shot 2015-03-20 at 1 07 03 pm](https://cloud.githubusercontent.com/assets/5309692/6760042/6266d75c-cf02-11e4-956f-3415bd35125f.png)

In hindsight, `{siteUrl}` isn't really used anymore in these circumstances... Now, it's more often referred to as `{baseUrl}`.

**Comment by engram-design** [comment]
This is a great idea! Hadn't even thought about this :) Seems reasonably feasible.

**Comment by lindseydiloreto** [comment]
Check out how I did it in the [CP CSS plugin...](https://github.com/lindseydiloreto/craft-cpcss/blob/master/cpcss/CpCssPlugin.php#L82) it's actually pretty straightforward!

**Comment by engram-design** [comment]
Nice one - that's pretty nifty!

**Comment by engram-design** [comment]
Hmmm - I'm no experts, but shouldn't this work in `modifyCpNav()`?

`
$nav[$newNav->handle] = array(
    'label' => $newNav->currLabel,
    'url'   => craft()->config->parseEnvironmentString(trim($newNav->url)),
);
`

Just keeps outputting the raw `{siteUrl}` tag...

**Comment by lindseydiloreto** [comment]
Do you have `siteUrl` defined in your [environment variables](http://buildwithcraft.com/docs/multi-environment-configs#environment-specific-variables)? If not, it won't get parsed out at all.

To be honest, I kinda misspoke when I said `siteUrl`... These days, it's almost always referenced as **`baseUrl`**. There was a lot of confusion back in the day about what "siteUrl" meant in different contexts, so Brandon tweaked the docs to make "baseUrl" the standard for environment variables.

**Comment by engram-design** [comment]
Yeah, I have it defined, I've also tried baseUrl, which I've defined too. Strange.

**Comment by lindseydiloreto** [comment]
Weird, I'd think that would work.

Does your `{baseUrl}` tag contain any spaces? It shouldn't.

Try this for debugging:

    $url = craft()->config->parseEnvironmentString(trim($newNav->url));

    Craft::dd($url);

    $nav[$newNav->handle] = array(
        'label' => $newNav->currLabel,
        'url'   => $url,
    );

What does that output?

**Comment by engram-design** [comment]
I'm using `$url = craft()->config->parseEnvironmentString('{baseUrl}/test');` just to be extra sure. It outputs `{baseUrl}/test`. What about you?

**Comment by lindseydiloreto** [comment]
I'm actually not testing on my end, but what you have looks right. Might be worth emailing P&T to find out what might be going on.

I feel like there's a 1% chance that perhaps the environment variables just haven't been set by the time `modifyCpNav` is called. Seems strange and unlikely, but I can't imagine what else might be causing the problem.

**Comment by lindseydiloreto** [comment]
Looks like you got this working beautifully!

It's only acting weird when you initially make the change... though I'm assuming it's using JS to change the nav tabs instantly.

**Comment by engram-design** [comment]
Good point, thats now fixed as well.

**Comment by badlydrawnrob** [comment]
Should `{siteUrl}` or `{baseUrl}` be working out of the box? Or do I have to modify something? It's just outputting `trigger/{siteUrl}/path` at the moment ...

**Comment by lindseydiloreto** [comment]
@badlydrawnrob: You'll need to have `{baseUrl}` defined in your [environment variables...](https://craftcms.com/docs/multi-environment-configs#environment-specific-variables)

**Comment by engram-design** [comment]
I'd love to have `{siteUrl}` available, but couldn't get it to work from memory. Might have another crack. In the meantime, as @lindseydiloreto points out, the `{baseUrl}` in your environment variables works a treat.

**Comment by badlydrawnrob** [comment]
@engram-design yup, would be handy to have if it's doable. @lindseydiloreto Hmm, `{baseUrl}` is defined but it just isn't working for me (outputting as if it's a relative url as I've mentioned earlier). I have `cpTrigger` set, some front-end form settings and the following:

    '.dev' => array(
      'devMode' => true,
      'siteUrl' => 'http://site.dev/',

      'environmentVariables' => array(
        'basePath' => '/home/vagrant/site/html/',
        'baseUrl'  => 'http://site.dev/',
      ),
      'enableTemplateCaching' => false,
    ),

**Comment by engram-design** [comment]
@badlydrawnrob Ah - you're certainly correct, there's a minor bug that caused this, which is now fixed in the [1.7.2 release](https://github.com/engram-design/CPNav/releases/tag/1.7.2)

**Comment by badlydrawnrob** [comment]
@engram-design Perfect. That'll save me some headaches between dev/live deploys :+1:

**Comment by engram-design** [comment]
FYI - `{siteUrl}` is now supported in the [1.7.3 release](https://github.com/engram-design/CPNav/releases/tag/1.7.3).
