### ISSUE TITLE
Dividers sometimes don't appear

### ISSUE THREAD

**Issue by JayBox325** [engram-design/CPNav#82]
**Description**
I have a sidebar built with some section dividers and they don't always seem to be rendering. See the screenshot below:

![Screenshot 2020-11-13 at 18 23 23](https://user-images.githubusercontent.com/13233809/99107328-8f78f080-25dd-11eb-948f-2b9086902bff.png)

The HTML elements are in the DOM, but they're not showing. This is happening in both Firefox and Chrome.

**Steps to reproduce**
1. Build a nav with dividers
2. Refresh the page a few times
3. Notice that the sidebar dividers doesn't always show

**Additional info**
- Plugin version: 3.0.13.1
- Craft version: 3.5.14
- Multi-site: No

**Comment by engram-design** [comment]
Sounds like the CSS isn't being applied. Are there are console errors?

Can you inspect the element and verify if it looks similar to https://d.pr/i/uxPfqk

**Comment by JayBox325** [comment]
Ok, yeah. That makes sense. It seems to be random when it happens or not. I tried to narrow down any potential causes to add to my ticket, but couldn't find any.

Next time it happens, I'll check the DOM and any CSS.

**Comment by JayBox325** [comment]
Some screens: 
![Screenshot 2020-11-30 at 16 20 55](https://user-images.githubusercontent.com/13233809/100635232-2fe24b00-3328-11eb-8938-72e035532e00.png)
![Screenshot 2020-11-30 at 16 20 48](https://user-images.githubusercontent.com/13233809/100635238-31ac0e80-3328-11eb-82ba-c49ff6844279.png)

**Comment by engram-design** [comment]
So no web developer console errors, or network errors? It looks like the JS isn't kicking in and adding the following classes `cpn-empty-url cpn-divider loaded` to the `nav-divider` element.

**Comment by engram-design** [comment]
Fixed in [3.0.16](https://github.com/verbb/cp-nav/releases/tag/3.0.16)
