### ISSUE TITLE
"Globals" nav missing "sel" class on select/active

### ISSUE THREAD

**Issue by richhayler** [engram-design/CPNav#88]
### Description
Selecting the "globals" nav In the control panel sidebar navigation doesn't attach the class "sel" to the nested anchor element.

## Steps to Reproduce
- Go to "layouts" and create a new layout 
- Click "Globals" in the Control Panel Sidebar and inspecting the HTML source will reveal that the "sel" class is missing from the nav item

The example below is what the code should look like when the nav item is selected.

```
<li id="nav-globals">
<a class="sel" href=".../globals/global">
<span class="icon icon-mask" aria-hidden="true"><span data-icon="globe"></span></span>
<span class="label">Globals</span></a>
</li>
```

Disabling the Control Panel Nav plugin restores the correct behaviour to the sidebar nav for the Globals nav item.

### Additional info

- Craft version: 3.6.10
- Control Panel Nav version: 3.0.15

**Comment by engram-design** [comment]
Fixed in [3.0.16](https://github.com/verbb/cp-nav/releases/tag/3.0.16)
