### ISSUE TITLE
[Bug] Renaming Globals

### ISSUE THREAD

**Issue by darylknight** [engram-design/CPNav#9]
Discovered an issue yesterday which I *think* needs fixing in CPNav rather than somewhere else. I created a global set called "Social Networks" to contain Facebook and Twitter links for the site. Handle name was socialNetworks.

Later, I renamed that global set handle to 'social'. In Craft, when you visit the Globals panel, the URL you get sent to is automatically set to the handle of the first global field set in use i.e. http://craft.dev/admin/globals/camelCase.

When I renamed the global field set, CPNav still tried to send me to http://store.craft.dev/castle/globals/socialNetworks, but it should be sending me to http://store.craft.dev/castle/globals/social. Uninstalling and reinstalling the plugin fixed the error. Is there a way to update this dynamically?

**Comment by engram-design** [comment]
Ah yes, thats a good point. Globals is the only menu item that does this special redirect-to-first-child thing. In fact, if you try to visit http://store.craft.dev/castle/globals, it will throw a 404. It would be a whole lot easier if this was the case.

Anyway, I've fixed this in the latest commit.

**Comment by darylknight** [comment]
Perfect! Fixed, tested.
