### ISSUE TITLE
Hello :)

### ISSUE THREAD

**Issue by wmdhosting** [engram-design/CPNav#90]
Hello :)

Started getting again error
I get the error https://prnt.sc/10u54ru

Brad told me, can be other places that need orginal fix..

Thx for help..

Additional info
Control Panel Nav 3.0.15
Craft Pro 3.6.10

_Originally posted by @wmdhosting in https://github.com/verbb/cp-nav/issues/84#issuecomment-809583878_

**Comment by engram-design** [comment]
Sorry for the delay. Difficult to tell what this is referring to from the CP-based error. If you're still having this issue, can you look in your `storage/logs/web.log` or `storage/logs/cp-nav.log` files for this error?

Was this also an upgrade from Craft, or CP plugin version?

**Comment by wmdhosting** [comment]
https://github.com/verbb/cp-nav/issues/84#issuecomment-809583878 

Here you fixed  previously.  
but seems need to do same on some other places..

**Comment by engram-design** [comment]
Fixed in [3.0.17](https://github.com/verbb/cp-nav/releases/tag/3.0.17)
