### ISSUE TITLE
switching layouts from preview to default while editing layout

### ISSUE THREAD

**Issue by ballmannweber** [engram-design/CPNav#91]
hi there, 

we installed 3.0.15 on craft pro 3.6.15 and created a new layout. while configuring the layout it never previews it. it does this only if we switch back to default in the navigation tab and switch back to our custom layout. as soon as we create a new divider or item and save this, it switches the preview back to default. 

also changing the order of items while the new layout is previewed switches the view back to default immediately.

**Comment by engram-design** [comment]
I can't seem to replicate this. Can you confirm what you're seeing in the red label above the nav each time you switch layouts?

![image](https://user-images.githubusercontent.com/1221575/120091005-46882400-c14a-11eb-8f14-6562bc87e776.png)

**Comment by ballmannweber** [comment]
the error disappeared with the new update :-)
