### ISSUE TITLE
Plugin Store link doesn't appear on envrionments with allowAdminChanges => false

### ISSUE THREAD

**Issue by darylknight** [engram-design/CPNav#92]
**Description**
Since 3.6.0, The Plugin Store link has been visible in the sidebar on sites with allowAdminChanges disabled, to allow people to purchase plugins on production. With CP Nav enabled, the Plugin Store link disappears.

**Steps to reproduce**
1. Install CPNav
2. The link to the Plugin Store disappears on sites with allowAdminChanges disabled

**Additional info**
- Plugin version: 3.0.16
- Craft version: 3.6.17
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [3.0.17](https://github.com/verbb/cp-nav/releases/tag/3.0.17)
