### ISSUE TITLE
Standard craft nav items don't show

### ISSUE THREAD

**Issue by joepagan** [engram-design/CPNav#93]
**Description**

Some of the standard dashboard nav items are missing: entries, categories, global, assets
To rectify this I have tried to add them manually, but they don't come through.
Forgive me if I'm doing something down right stupid

![image](https://user-images.githubusercontent.com/2337910/124950719-93dd9800-e00a-11eb-9e13-2ce02e8d0b00.png)
![image](https://user-images.githubusercontent.com/2337910/124950764-9f30c380-e00a-11eb-8793-cf59b5ffcb5a.png)

**Steps to reproduce**
1. install plugin - no lose default nav items
2. add manually - they still don't appear

**Additional info**
- Plugin version: 3.0.17
- Craft version: 3.6.17
- Multi-site: No

**Additional context**

tried urls with a prefixed `/` and not

**Comment by joepagan** [comment]
Ok turns out I was being a fool. 

Haven't setup a base craft site for a long time and just found out no entries exist from a fresh install and these items are genuinely hidden even if cp-nav plugin is disabled.

That said, if I have manually created the nav item to `entries` in cp-nav and no entries exist, I would have expected the nav item to still exist regardless of craft's default behavior?

**Comment by engram-design** [comment]
It's mostly because in-built nav items (from Craft itself, or plugins) are classified as special nav items, as opposed to user-created ones, so they're really two different things. I'll look into supporting this behaviour though.

I would also suggest rebuilding your cp-nav, but sounds like you've got it sorted for the moment.
