### ISSUE TITLE
Make divider label optional

### ISSUE THREAD

**Issue by anchovy** [engram-design/CPNav#95]
**What are you trying to do?**
Sometimes we want to have a divider with no name to indicate the end of a block of related menu items
i.e. 
-Users------
Users
- Fields (custom)
- Imports (custom)
- etc.
- etc.
------------- (blank divider)
Utilities
Settings
Plugin Store

**What's your proposed solution?**
Make the Label on the divider field optional.

**Additional context**

**Comment by engram-design** [comment]
Added in [4.0.0-beta.2](https://github.com/verbb/cp-nav/releases/tag/4.0.0-beta.2) for Craft 4.
