### ISSUE TITLE
Duplicated CP navigation entries

### ISSUE THREAD

**Issue by scandella** [engram-design/CPNav#96]
**Description**
Everytime I sync the project files, all the CP navigation entries are duplicated.
I have to reset the Control Panel Nav settings, which makes the custom settings useless…

**Steps to reproduce**
1. Update the project files
2. The CP navigation entries are duplicated
3. Update the project files again
4. Each CP navigation entries appears now three times and so on…

**Additional info**
- Plugin version: 3.0.17
- Craft version: Craft Pro 3.7.14
- Multi-site: No

**Additional context**

**Comment by darylknight** [comment]
This sounds like it might be an environment / Project Config issue rather than specific to CP nav - I can't replicate it. What do you mean by "sync the project files"?

**Comment by engram-design** [comment]
Should be improved in [4.0.0-beta.2](https://github.com/verbb/cp-nav/releases/tag/4.0.0-beta.2) for Craft 4.
