### ISSUE TITLE
Entries link keeps disappearing

### ISSUE THREAD

**Issue by adrienne** [engram-design/CPNav#99]
**Description**

As of the Craft 3.7.30 upgrade, the Entries link keeps disappearing from all custom navbars. We keep re-adding it and it keeps disappearing. Any thoughts?

**Comment by engram-design** [comment]
That seems odd! I'll have to take a look, and might be handled by some major updates already in development.

I can't seem to replicate it though, and it sounds like it might be one of those annoying sporadic ones? Are you switching users or anything like that?

**Comment by engram-design** [comment]
Should be fixed in [4.0.0-beta.2](https://github.com/verbb/cp-nav/releases/tag/4.0.0-beta.2) for Craft 4.
